# Generated by Django 4.0.1 on 2022-04-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class1',
            old_name='date',
            new_name='buy_date',
        ),
    ]
