# Generated by Django 4.0.1 on 2022-03-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_userinfo_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='names',
            new_name='xingming',
        ),
    ]
