# Generated by Django 4.0.1 on 2022-03-31 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_names_userinfo_xingming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='xingming',
            new_name='names',
        ),
    ]
