# Generated by Django 4.0.1 on 2022-03-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_xingming_userinfo_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='names',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
