# Generated by Django 4.0.1 on 2022-04-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userinfo_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='names',
            new_name='name',
        ),
    ]
